version: '3'

dotenv: ['.env']

tasks:
  format:py:
    desc: Format python code
    cmds:
      - find -name '**.py' | xargs poetry run isort --profile black
      - find -name '**.py' | xargs poetry run black

  format:
    desc: Format code
    cmds:
      - task: format:py

  env-setup:
    desc: Install env
    cmds:
      - poetry install

  request-input:
    desc: Request input from AoC
    cmds:
      - poetry run python request-input.py {{.CLI_ARGS}}


